CREATE DATABASE DMES
  WITH OWNER = "sipPrueba"
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'es_CO.UTF-8'
       LC_CTYPE = 'es_CO.UTF-8'
       CONNECTION LIMIT = -1;


CREATE ROLE "sipPrueba" LOGIN
  ENCRYPTED PASSWORD 'md5b9532225a17272475cf141bc90f7fc94'
  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;



CREATE SCHEMA DMES
  AUTHORIZATION "sipPrueba";


-- Table: DMES.SC_COMPANY

-- DROP TABLE DMES.SC_COMPANY;

CREATE TABLE DMES.SC_COMPANY
(
  ID_COMPANY numeric(18,0) NOT NULL,
  NAME character varying(100) NOT NULL,
  DESCRIPTION character varying(2000),
  CONSTRAINT PK_COMPANY PRIMARY KEY (ID_COMPANY)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_COMPANY
  OWNER TO "sipPrueba";


-- Table: DMES.SC_COMPETENCIES

-- DROP TABLE DMES.SC_COMPETENCIES;

CREATE TABLE DMES.SC_COMPETENCIES
(
  ID_COMPETENCIES numeric(18,0) NOT NULL,
  TITTLE character varying(100) NOT NULL,
  DESCRIPTION character varying(2000),
  ID_EMPLOYEE numeric(18,0) NOT NULL,
  CONSTRAINT PK_COMPETENCIES PRIMARY KEY (ID_COMPETENCIES),
  CONSTRAINT ID_COMPETENCIES_EMPLOYEE FOREIGN KEY (ID_EMPLOYEE)
      REFERENCES DMES.SC_EMPLOYEE (ID_EMPLOYEE) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_COMPETENCIES
  OWNER TO "sipPrueba";



-- Table: DMES.SC_EMPLOYEE

-- DROP TABLE DMES.SC_EMPLOYEE;

CREATE TABLE DMES.SC_EMPLOYEE
(
  ID_EMPLOYEE numeric(18,0) NOT NULL,
  POSITION character varying(100) NOT NULL,
  FORMATION character varying(100) NOT NULL,
  ADMISSION_DATE date NOT NULL,
  RETIREMENT_DATE date,
  ACTIVE character(1) NOT NULL,
  SALARY numeric(18,2),
  HOUR_VALUE numeric(18,2),
  PORCENTAGE numeric(18,2),
  AMOUNT numeric(18,2),
  CREATION_DATE date NOT NULL,
  MODIFY_DATE date,
  ID_PERSON numeric(18,0) NOT NULL,
  CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID_EMPLOYEE),
  CONSTRAINT FK_EMPLOYEE_PERSON FOREIGN KEY (ID_PERSON)
      REFERENCES DMES.SC_PERSON (ID_PERSON) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_EMPLOYEE
  OWNER TO "sipPrueba";



-- Table: DMES.SC_MAILS

-- DROP TABLE DMES.SC_MAILS;

CREATE TABLE DMES.SC_MAILS
(
  ID_MAIL numeric(18,0) NOT NULL,
  MAIL character varying(100) NOT NULL,
  DESCRIPTION character varying(100),
  ID_PERSON numeric(18,0) NOT NULL,
  CONSTRAINT PK_MAILS PRIMARY KEY (ID_MAIL),
  CONSTRAINT FK_MAILS_PERSON FOREIGN KEY (ID_PERSON)
      REFERENCES DMES.SC_PERSON (ID_PERSON) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_MAILS
  OWNER TO "sipPrueba";



-- Table: DMES.SC_MODULE_PERMISSION

-- DROP TABLE DMES.SC_MODULE_PERMISSION;

CREATE TABLE sc_module_permission (id_module_permission numeric(18) NOT NULL, 
"name" varchar(100) NOT NULL, description varchar(2000), icone varchar(2000), "type" varchar(50),
 id_father numeric(18), page varchar(50), PRIMARY KEY (id_module_permission));




-- Table: DMES.SC_MODULE_PERMISSION_BY_ROLE

-- DROP TABLE DMES.SC_MODULE_PERMISSION_BY_ROLE;

CREATE TABLE DMES.SC_MODULE_PERMISSION_BY_ROLE
(
  ID_MODULE_PERMISSION_BY_ROLE numeric(18,0) NOT NULL,
  ID_ROLE numeric(18,0) NOT NULL,
  ID_TYPE character varying(5),
  ID_MODULE_PERMISSION numeric(18,0) NOT NULL,
  CONSTRAINT PK_MODULE_PERMISSION_BY_ROLE PRIMARY KEY (ID_MODULE_PERMISSION_BY_ROLE),
  CONSTRAINT FK_MODULE_PERMISSION FOREIGN KEY (ID_MODULE_PERMISSION)
      REFERENCES DMES.SC_MODULE_PERMISSION (ID_MODULE_PERMISSION) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_MODULE_PERMISSION_BY_ROLE_FOR_ROLE FOREIGN KEY (ID_ROLE)
      REFERENCES DMES.SC_ROLES (ID_ROL) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_MODULE_PERMISSION_BY_ROLE
  OWNER TO "sipPrueba";



-- Table: DMES.SC_PARTNER

-- DROP TABLE DMES.SC_PARTNER;

CREATE TABLE DMES.SC_PARTNER
(
  ID_PARTNER numeric(18,0) NOT NULL,
  ID_COMPANY numeric(18,0) NOT NULL,
  ACTIVE character varying(1) NOT NULL,
  POSITION character varying(100) NOT NULL,
  WEB_PAGE character varying(100),
  CREATION_DATE date NOT NULL,
  MODIFY_DATE date,
  ID_PERSON numeric(18,0) NOT NULL,
  CONSTRAINT PK_PARTNER PRIMARY KEY (ID_PARTNER),
  CONSTRAINT FK_PARTNER_COMPANY FOREIGN KEY (ID_COMPANY)
      REFERENCES DMES.SC_COMPANY (ID_COMPANY) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_PARTNER_PERSON FOREIGN KEY (ID_PERSON)
      REFERENCES DMES.SC_PERSON (ID_PERSON) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_PARTNER
  OWNER TO "sipPrueba";


-- Table: DMES.SC_PERSON

-- DROP TABLE DMES.SC_PERSON;

CREATE TABLE DMES.SC_PERSON
(
  ID_PERSON numeric(18,0) NOT NULL,
  FIRST_NAME character varying(100) NOT NULL,
  LAST_NAME character varying(100) NOT NULL,
  AGE numeric(3,0) NOT NULL,
  COUNTRY character varying(100) NOT NULL,
  CITY character varying(100) NOT NULL,
  PERSONAL_INFORMATION character varying(2000),
  DOMICILIE character varying(100) NOT NULL,
  STUDIES character varying(2000),
  DESCRIPTION character varying(2000),
  PATH_PHOTO character varying NOT NULL,
  CREATION_DATE date NOT NULL,
  MODIFY_DATE date,
  CONSTRAINT PK_PERSON PRIMARY KEY (ID_PERSON)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_PERSON
  OWNER TO "sipPrueba";


-- Table: DMES.SC_PERSON_DOCUMENTATION_ATTACHED

-- DROP TABLE DMES.SC_PERSON_DOCUMENTATION_ATTACHED;

CREATE TABLE DMES.SC_PERSON_DOCUMENTATION_ATTACHED
(
  ID_PERSON_DOCUMENTATION_ATTACHED numeric(18,0) NOT NULL,
  TITTLE character varying(200) NOT NULL,
  PATH character varying(2000) NOT NULL,
  ID_PERSON numeric(18,0) NOT NULL,
  CONSTRAINT PK_PERSON_DOCUMENTATION_ATTACHED PRIMARY KEY (ID_PERSON_DOCUMENTATION_ATTACHED),
  CONSTRAINT FK_PERSON_DOCUMENTATION_ATTACHED_FOR_PERSON FOREIGN KEY (ID_PERSON)
      REFERENCES DMES.SC_PERSON (ID_PERSON) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_PERSON_DOCUMENTATION_ATTACHED
  OWNER TO "sipPrueba";


-- Table: DMES.SC_PERSON_OBSERVATIONS

-- DROP TABLE DMES.SC_PERSON_OBSERVATIONS;

CREATE TABLE DMES.SC_PERSON_OBSERVATIONS
(
  ID_PERSON_OBSERVATIONS numeric(18,0) NOT NULL,
  TITTLE character varying(200) NOT NULL,
  OBSERVATION character varying(2000) NOT NULL,
  ID_PERSON numeric(18,0) NOT NULL,
  CONSTRAINT PK_PERSON_OBSERVATIONS PRIMARY KEY (ID_PERSON_OBSERVATIONS),
  CONSTRAINT FK_PERSON_OBSERVATION_FOR_PERSON FOREIGN KEY (ID_PERSON)
      REFERENCES DMES.SC_PERSON (ID_PERSON) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_PERSON_OBSERVATIONS
  OWNER TO "sipPrueba";


-- Table: DMES.SC_PERSON_SPECIFICATIONS

-- DROP TABLE DMES.SC_PERSON_SPECIFICATIONS;

CREATE TABLE DMES.SC_PERSON_SPECIFICATIONS
(
  ID_PERSON_SPECIFICATIONS numeric(18,0) NOT NULL,
  TITTLE character varying(200) NOT NULL,
  SPECIFICATION character varying(2000) NOT NULL,
  ID_PERSON numeric(18,0) NOT NULL,
  CONSTRAINT PK_PERSON_SPECIFICATIONS PRIMARY KEY (ID_PERSON_SPECIFICATIONS),
  CONSTRAINT FK_PERSON_SPECIFICATIONS_FOR_PERSON FOREIGN KEY (ID_PERSON)
      REFERENCES DMES.SC_PERSON (ID_PERSON) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_PERSON_SPECIFICATIONS
  OWNER TO "sipPrueba";


-- Table: DMES.SC_PHONES

-- DROP TABLE DMES.SC_PHONES;

CREATE TABLE DMES.SC_PHONES
(
  ID_PHONE numeric(18,0) NOT NULL,
  NUMBER_PHONE numeric(18,0) NOT NULL,
  DESCRIPTION character varying(100),
  ID_PERSON numeric(18,0) NOT NULL,
  CONSTRAINT PK_PHONES PRIMARY KEY (ID_PHONE),
  CONSTRAINT FK_PHONES_PERSON FOREIGN KEY (ID_PERSON)
      REFERENCES DMES.SC_PERSON (ID_PERSON) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_PHONES
  OWNER TO "sipPrueba";


-- Table: DMES.SC_ROLES

-- DROP TABLE DMES.SC_ROLES;

CREATE TABLE DMES.SC_ROLES
(
  ID_ROL numeric(18,0) NOT NULL,
  NAME character varying(100) NOT NULL,
  DESCRIPTION character varying(2000),
  CREATION_DATE date NOT NULL,
  MODIFY_DATE date,
  CONSTRAINT PK_SC_ROLES PRIMARY KEY (ID_ROL)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_ROLES
  OWNER TO "sipPrueba";


-- Table: DMES.SC_SERVICES_OR_PRODUCTS

-- DROP TABLE DMES.SC_SERVICES_OR_PRODUCTS;

CREATE TABLE DMES.SC_SERVICES_OR_PRODUCTS
(
  ID_SERVICE_OR_PRODUCTS numeric(18,0) NOT NULL,
  NAME_SERVICE_OR_PRODUCT character varying(100) NOT NULL,
  COST numeric(18,2) NOT NULL,
  GUARANTEE character varying(2000),
  DESCRIPTION character varying(2000),
  AMOUNT numeric(18,0) NOT NULL,
  ID_PARTNER numeric(18,0) NOT NULL,
  TYPE character varying(100) NOT NULL,
  CONSTRAINT PK_SERVICE_OR_PRODUCT PRIMARY KEY (ID_SERVICE_OR_PRODUCTS),
  CONSTRAINT FK_SERVICE_OR_PRODUCT_PARTNER FOREIGN KEY (ID_PARTNER)
      REFERENCES DMES.SC_PARTNER (ID_PARTNER) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_SERVICES_OR_PRODUCTS
  OWNER TO "sipPrueba";


-- Table: DMES.SC_SUBMODULE_PERMISSION

-- Table: DMES.SC_USERS

-- DROP TABLE DMES.SC_USERS;

CREATE TABLE DMES.SC_USERS
(
  id_user numeric(18,0) NOT NULL,
  id_person numeric(18,0) NOT NULL,
  id_role numeric(18,0) NOT NULL,
  login character varying(100) NOT NULL,
  password character varying(100) NOT NULL,
  creation_date date NOT NULL,
  modify_date date,
  CONSTRAINT PK_USERS PRIMARY KEY (id_user),
  CONSTRAINT FK_PERSON FOREIGN KEY (id_person)
      REFERENCES DMES.SC_PERSON (ID_PERSON) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_ROLE FOREIGN KEY (id_role)
      REFERENCES DMES.SC_ROLES (ID_ROL) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_USERS
  OWNER TO "sipPrueba";


-- Table: DMES.SC_WORK_EXPERIENCE

-- DROP TABLE DMES.SC_WORK_EXPERIENCE;

CREATE TABLE DMES.SC_WORK_EXPERIENCE
(
  ID_WORK_EXPERIENCE numeric(18,0) NOT NULL,
  ID_COMPANY numeric(18,0) NOT NULL,
  INIT_DATE date NOT NULL,
  END_DATE date NOT NULL,
  ID_EMPLOYEE numeric(18,0) NOT NULL,
  CONSTRAINT PK_WORK_EXPERIENCE PRIMARY KEY (ID_WORK_EXPERIENCE),
  CONSTRAINT FK_WORK_EXPERIENCE_COMPANY FOREIGN KEY (ID_COMPANY)
      REFERENCES DMES.SC_COMPANY (ID_COMPANY) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_WORK_EXPERIENCE_EMPLOYEE FOREIGN KEY (ID_EMPLOYEE)
      REFERENCES DMES.SC_EMPLOYEE (ID_EMPLOYEE) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DMES.SC_WORK_EXPERIENCE
  OWNER TO "sipPrueba";


INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (1, 'Visibilidad de Planta', NULL, 'bar.png', 'Home', -1, 'mainMenu');
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (2, 'Visibilidad de Planta', NULL, 'oee.png', 'Folder', 1, NULL);
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (3, 'Programación de Orden de Fabricación', NULL, 'ord.png', 'Folder', 1, NULL);
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (4, 'estión de la Calidad y la Trazabilidad', NULL, 'cal.png', 'Folder', 1, NULL);
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (5, 'Gestión del Mantenimiento', NULL, 'man.png', 'Folder', 1, NULL);
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (6, 'Gestión de los Recursos', NULL, 'rec.png', 'Folder', 1, NULL);
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (7, 'Configuraciones', NULL, 'confi.png', 'Folder', 1, NULL);
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (9, 'Recursos Humanos', '', NULL, 'Folder', 7, NULL);
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (10, 'Recursos Materiales', NULL, NULL, 'Folder', 7, NULL);
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (8, 'Cerrar Sesión', NULL, 'salir.png', 'Folder', 1, 'exit');
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (11, 'Empleados', NULL, NULL, 'Item', 9, 'employee');
INSERT INTO dmes.sc_module_permission (id_module_permission, "name", description, icone, "type", id_father, page) 
	VALUES (12, 'Proveedores', NULL, NULL, 'Item', 9, 'partner');


INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (1, 1, 'CRUD', 1);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (2, 1, 'CRUD', 2);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (3, 1, 'CRUD', 3);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (4, 1, 'CRUD', 4);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (5, 1, 'CRUD', 5);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (6, 1, 'CRUD', 6);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (7, 1, 'CRUD', 7);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (8, 1, 'CRUD', 8);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (9, 1, 'CRUD', 9);

INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (10, 1, 'CRUD', 10);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (11, 1, 'CRUD', 11);
INSERT INTO DMES.SC_MODULE_PERMISSION_BY_ROLE (ID_MODULE_PERMISSION_BY_ROLE, ID_ROLE, ID_TYPE, ID_MODULE_PERMISSION) 
	VALUES (12, 1, 'CRUD', 12);

INSERT INTO dmes.sc_roles (id_role, "name", description, creation_date, modify_date) 
	VALUES (1, 'Administrator', NULL, '2014-09-26', NULL);

INSERT INTO dmes.sc_users (id_user, id_person, id_role, login, password, creation_date, modify_date) 
	VALUES (1, 1, 1, 'guschaor', '4e991c769a2b9a881189cd86c160b604', '2014-07-26', NULL);

