
CREATE TABLE "DMES"."SC_ROLES"
(
   "ID_ROL" numeric(18,0) NOT NULL, 
   "NAME" character varying(100) NOT NULL, 
   "DESCRIPTION" character varying(2000), 
   "CREATION_DATE" date NOT NULL, 
   "MODIFY_DATE" date, 
   CONSTRAINT "PK_SC_ROLES" PRIMARY KEY ("ID_ROL")
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_ROLES" OWNER TO "sipPrueba";

CREATE TABLE "DMES"."SC_MODULE_PERMISSION"
(
   "ID_MODULE_PERMISSION" numeric(18,0) NOT NULL, 
   "NAME" character varying(100) NOT NULL, 
   "DESCRIPTION" character varying(2000), 
   CONSTRAINT "PK_SC_MODULE_PERMISSION" PRIMARY KEY ("ID_MODULE_PERMISSION")
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_MODULE_PERMISSION" OWNER TO "sipPrueba";


CREATE TABLE "DMES"."SC_MODULE_PERMISSION_BY_ROLE"
(
  "ID_MODULE_PERMISSION_BY_ROLE" numeric(18,0) NOT NULL,
  "ID_ROLE" numeric(18,0) NOT NULL,
  "ID_MODULE_PERMISSION" numeric(18,0) NOT NULL,
  "TYPE_PERMISSION" character varying(10) NOT NULL,
  CONSTRAINT "PK_MODULE_PERMISSION_BY_ROLE" PRIMARY KEY ("ID_MODULE_PERMISSION_BY_ROLE" ),
  CONSTRAINT "FK_MODULE_PERMISSION_BY_ROLE_FOR_MODULE_PERMISSION" FOREIGN KEY ("ID_MODULE_PERMISSION")
      REFERENCES "DMES"."SC_MODULE_PERMISSION" ("ID_MODULE_PERMISSION") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_MODULE_PERMISSION_BY_ROLE_FOR_ROLE" FOREIGN KEY ("ID_ROLE")
      REFERENCES "DMES"."SC_ROLES" ("ID_ROLE") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "DMES"."SC_MODULE_PERMISSION_BY_ROLE"
  OWNER TO "sipPrueba";


CREATE TABLE "DMES"."SC_PERSON"
(
   "ID_PERSON" numeric(18,0) NOT NULL, 
   "FIRST_NAME" character varying(100) NOT NULL, 
   "LAST_NAME" character varying(100) NOT NULL, 
   "AGE" numeric(3,0) NOT NULL, 
   "COUNTRY" character varying(100) NOT NULL, 
   "CITY" character varying(100) NOT NULL, 
   "PERSONAL_INFORMATION" character varying(2000), 
   "DOMICILIE" character varying(100) NOT NULL, 
   "STUDIES" character varying(2000), 
   "DESCRIPTION" character varying(2000), 
   "PATH_PHOTO" character varying NOT NULL, 
   "CREATION_DATE" date NOT NULL, 
   "MODIFY_DATE" date, 
   CONSTRAINT "PK_PERSON" PRIMARY KEY ("ID_PERSON")
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PERSON" OWNER TO "sipPrueba";


CREATE TABLE "DMES"."SC_PHONES"
(
   "ID_PHONE" numeric(18,0) NOT NULL, 
   "NUMBER_PHONE" numeric(18,0) NOT NULL, 
   "DESCRIPTION" character varying(100), 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_PHONES" PRIMARY KEY ("ID_PHONE"), 
   CONSTRAINT "FK_PHONES_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PHONES" OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_MAILS"
(
   "ID_MAIL" numeric(18,0) NOT NULL, 
   "MAIL" character varying(100) NOT NULL, 
   "DESCRIPTION" character varying(100), 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_MAILS" PRIMARY KEY ("ID_MAIL"), 
   CONSTRAINT "FK_MAILS_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_MAILS" OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_PERSON_OBSERVATIONS"
(
   "ID_PERSON_OBSERVATIONS" numeric(18,0) NOT NULL, 
   "TITTLE" character varying(200) NOT NULL, 
   "OBSERVATION" character varying(2000) NOT NULL, 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_PERSON_OBSERVATIONS" PRIMARY KEY ("ID_PERSON_OBSERVATIONS"), 
   CONSTRAINT "FK_PERSON_OBSERVATION_FOR_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PERSON_OBSERVATIONS" OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_PERSON_DOCUMENTATION_ATTACHED"
(
   "ID_PERSON_DOCUMENTATION_ATTACHED" numeric(18,0) NOT NULL, 
   "TITTLE" character varying(200) NOT NULL, 
   "PATH" character varying(2000) NOT NULL, 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_PERSON_DOCUMENTATION_ATTACHED" PRIMARY KEY ("ID_PERSON_DOCUMENTATION_ATTACHED"), 
   CONSTRAINT "FK_PERSON_DOCUMENTATION_ATTACHED_FOR_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PERSON_DOCUMENTATION_ATTACHED" OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_PERSON_SPECIFICATIONS"
(
   "ID_PERSON_SPECIFICATIONS" numeric(18,0) NOT NULL, 
   "TITTLE" character varying(200) NOT NULL, 
   "SPECIFICATION" character varying(2000) NOT NULL, 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_PERSON_SPECIFICATIONS" PRIMARY KEY ("ID_PERSON_SPECIFICATIONS"), 
   CONSTRAINT "FK_PERSON_SPECIFICATIONS_FOR_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PERSON_SPECIFICATIONS" OWNER TO "sipPrueba";

	
