
CREATE TABLE "DMES"."SC_ROLES"
(
   "ID_ROL" numeric(18,0) NOT NULL, 
   "NAME" character varying(100) NOT NULL, 
   "DESCRIPTION" character varying(2000), 
   "CREATION_DATE" date NOT NULL, 
   "MODIFY_DATE" date, 
   CONSTRAINT "PK_SC_ROLES" PRIMARY KEY ("ID_ROL")
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_ROLES" OWNER TO "sipPrueba";

CREATE TABLE "DMES"."SC_MODULE_PERMISSION"
(
   "ID_MODULE_PERMISSION" numeric(18,0) NOT NULL, 
   "NAME" character varying(100) NOT NULL, 
   "DESCRIPTION" character varying(2000), 
   CONSTRAINT "PK_SC_MODULE_PERMISSION" PRIMARY KEY ("ID_MODULE_PERMISSION")
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_MODULE_PERMISSION" OWNER TO "sipPrueba";


CREATE TABLE "DMES"."SC_MODULE_PERMISSION_BY_ROLE"
(
  "ID_MODULE_PERMISSION_BY_ROLE" numeric(18,0) NOT NULL,
  "ID_ROLE" numeric(18,0) NOT NULL,
  "ID_MODULE_PERMISSION" numeric(18,0) NOT NULL,
  "TYPE_PERMISSION" character varying(10) NOT NULL,
  CONSTRAINT "PK_MODULE_PERMISSION_BY_ROLE" PRIMARY KEY ("ID_MODULE_PERMISSION_BY_ROLE" ),
  CONSTRAINT "FK_MODULE_PERMISSION_BY_ROLE_FOR_MODULE_PERMISSION" FOREIGN KEY ("ID_MODULE_PERMISSION")
      REFERENCES "DMES"."SC_MODULE_PERMISSION" ("ID_MODULE_PERMISSION") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_MODULE_PERMISSION_BY_ROLE_FOR_ROLE" FOREIGN KEY ("ID_ROLE")
      REFERENCES "DMES"."SC_ROLES" ("ID_ROLE") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "DMES"."SC_MODULE_PERMISSION_BY_ROLE"
  OWNER TO "sipPrueba";


CREATE TABLE "DMES"."SC_PERSON"
(
   "ID_PERSON" numeric(18,0) NOT NULL, 
   "FIRST_NAME" character varying(100) NOT NULL, 
   "LAST_NAME" character varying(100) NOT NULL, 
   "AGE" numeric(3,0) NOT NULL, 
   "COUNTRY" character varying(100) NOT NULL, 
   "CITY" character varying(100) NOT NULL, 
   "PERSONAL_INFORMATION" character varying(2000), 
   "DOMICILIE" character varying(100) NOT NULL, 
   "STUDIES" character varying(2000), 
   "DESCRIPTION" character varying(2000), 
   "PATH_PHOTO" character varying NOT NULL, 
   "CREATION_DATE" date NOT NULL, 
   "MODIFY_DATE" date, 
   CONSTRAINT "PK_PERSON" PRIMARY KEY ("ID_PERSON")
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PERSON" OWNER TO "sipPrueba";


CREATE TABLE "DMES"."SC_PHONES"
(
   "ID_PHONE" numeric(18,0) NOT NULL, 
   "NUMBER_PHONE" numeric(18,0) NOT NULL, 
   "DESCRIPTION" character varying(100), 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_PHONES" PRIMARY KEY ("ID_PHONE"), 
   CONSTRAINT "FK_PHONES_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PHONES" OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_MAILS"
(
   "ID_MAIL" numeric(18,0) NOT NULL, 
   "MAIL" character varying(100) NOT NULL, 
   "DESCRIPTION" character varying(100), 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_MAILS" PRIMARY KEY ("ID_MAIL"), 
   CONSTRAINT "FK_MAILS_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_MAILS" OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_PERSON_OBSERVATIONS"
(
   "ID_PERSON_OBSERVATIONS" numeric(18,0) NOT NULL, 
   "TITTLE" character varying(200) NOT NULL, 
   "OBSERVATION" character varying(2000) NOT NULL, 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_PERSON_OBSERVATIONS" PRIMARY KEY ("ID_PERSON_OBSERVATIONS"), 
   CONSTRAINT "FK_PERSON_OBSERVATION_FOR_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PERSON_OBSERVATIONS" OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_PERSON_DOCUMENTATION_ATTACHED"
(
   "ID_PERSON_DOCUMENTATION_ATTACHED" numeric(18,0) NOT NULL, 
   "TITTLE" character varying(200) NOT NULL, 
   "PATH" character varying(2000) NOT NULL, 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_PERSON_DOCUMENTATION_ATTACHED" PRIMARY KEY ("ID_PERSON_DOCUMENTATION_ATTACHED"), 
   CONSTRAINT "FK_PERSON_DOCUMENTATION_ATTACHED_FOR_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PERSON_DOCUMENTATION_ATTACHED" OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_PERSON_SPECIFICATIONS"
(
   "ID_PERSON_SPECIFICATIONS" numeric(18,0) NOT NULL, 
   "TITTLE" character varying(200) NOT NULL, 
   "SPECIFICATION" character varying(2000) NOT NULL, 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_PERSON_SPECIFICATIONS" PRIMARY KEY ("ID_PERSON_SPECIFICATIONS"), 
   CONSTRAINT "FK_PERSON_SPECIFICATIONS_FOR_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PERSON_SPECIFICATIONS" OWNER TO "sipPrueba";

CREATE TABLE "DMES"."SC_EMPLOYEE"
(
   "ID_EMPLOYEE" numeric(18,0) NOT NULL, 
   "POSITION" character varying(100) NOT NULL, 
   "FORMATION" character varying(100) NOT NULL, 
   "ADMISSION_DATE" date NOT NULL, 
   "RETIREMENT_DATE" date, 
   "ACTIVE" character(1) NOT NULL, 
   "SALARY" numeric(18,2), 
   "HOUR_VALUE" numeric(18,2), 
   "PORCENTAGE" numeric(18,2), 
   "AMOUNT" numeric(18,2), 
   "CREATION_DATE" date NOT NULL, 
   "MODIFY_DATE" date, 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY ("ID_EMPLOYEE"), 
   CONSTRAINT "FK_EMPLOYEE_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_EMPLOYEE"
  OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_COMPANY"
(
   "ID_COMPANY" numeric(18,0) NOT NULL, 
   "NAME" character varying(100) NOT NULL, 
   "DESCRIPTION" character varying(2000), 
   CONSTRAINT "PK_COMPANY" PRIMARY KEY ("ID_COMPANY")
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_COMPANY"
  OWNER TO "sipPrueba";
	

CREATE TABLE "DMES"."SC_PARTNER"
(
   "ID_PARTNER" numeric(18,0) NOT NULL, 
   "ID_COMPANY" numeric(18,0) NOT NULL, 
   "ACTIVE" character varying(1) NOT NULL, 
   "POSITION" character varying(100) NOT NULL, 
   "WEB_PAGE" character varying(100), 
   "CREATION_DATE" date NOT NULL, 
   "MODIFY_DATE" date, 
   "ID_PERSON" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_PARTNER" PRIMARY KEY ("ID_PARTNER"), 
   CONSTRAINT "FK_PARTNER_PERSON" FOREIGN KEY ("ID_PERSON") REFERENCES "DMES"."SC_PERSON" ("ID_PERSON") ON UPDATE NO ACTION ON DELETE NO ACTION, 
   CONSTRAINT "FK_PARTNER_COMPANY" FOREIGN KEY ("ID_COMPANY") REFERENCES "DMES"."SC_COMPANY" ("ID_COMPANY") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_PARTNER"
  OWNER TO "sipPrueba";



CREATE TABLE "DMES"."SC_WORK_EXPERIENCE"
(
  "ID_WORK_EXPERIENCE" numeric(18,0) NOT NULL,
  "ID_COMPANY" numeric(18,0) NOT NULL,
  "INIT_DATE" date NOT NULL,
  "END_DATE" date NOT NULL,
  "ID_EMPLOYEE" numeric(18,0) NOT NULL,
  CONSTRAINT "PK_WORK_EXPERIENCE" PRIMARY KEY ("ID_WORK_EXPERIENCE"),
  CONSTRAINT "FK_WORK_EXPERIENCE_COMPANY" FOREIGN KEY ("ID_COMPANY")
      REFERENCES "DMES"."SC_COMPANY" ("ID_COMPANY") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_WORK_EXPERIENCE_EMPLOYEE" FOREIGN KEY ("ID_EMPLOYEE")
      REFERENCES "DMES"."SC_EMPLOYEE" ("ID_EMPLOYEE") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "DMES"."SC_WORK_EXPERIENCE"
  OWNER TO "sipPrueba";


CREATE TABLE "DMES"."SC_COMPETENCIES"
(
   "ID_COMPETENCIES" numeric(18,0) NOT NULL, 
   "TITTLE" character varying(100) NOT NULL, 
   "DESCRIPTION" character varying(2000), 
   "ID_EMPLOYEE" numeric(18,0) NOT NULL, 
   CONSTRAINT "PK_COMPETENCIES" PRIMARY KEY ("ID_COMPETENCIES"), 
   CONSTRAINT "ID_COMPETENCIES_EMPLOYEE" FOREIGN KEY ("ID_EMPLOYEE") REFERENCES "DMES"."SC_EMPLOYEE" ("ID_EMPLOYEE") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_COMPETENCIES"
  OWNER TO "sipPrueba";


CREATE TABLE "DMES"."SC_SERVICES_OR_PRODUCTS"
(
   "ID_SERVICE_OR_PRODUCTS" numeric(18,0) NOT NULL, 
   "NAME_SERVICE_OR_PRODUCT" character varying(100) NOT NULL, 
   "COST" numeric(18,2) NOT NULL, 
   "GUARANTEE" character varying(2000), 
   "DESCRIPTION" character varying(2000), 
   "AMOUNT" numeric(18,0) NOT NULL, 
   "ID_PARTNER" numeric(18,0) NOT NULL, 
   "TYPE" character varying(100) NOT NULL, 
   CONSTRAINT "PK_SERVICE_OR_PRODUCT" PRIMARY KEY ("ID_SERVICE_OR_PRODUCTS"), 
   CONSTRAINT "FK_SERVICE_OR_PRODUCT_PARTNER" FOREIGN KEY ("ID_PARTNER") REFERENCES "DMES"."SC_PARTNER" ("ID_PARTNER") ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
ALTER TABLE "DMES"."SC_SERVICES_OR_PRODUCTS"
  OWNER TO "sipPrueba";
