INSERT INTO "DMES"."SC_MODULE_PERMISSION" ("ID_MODULE_PERMISSION", "NAME", "DESCRIPTION") 
	VALUES (1, 'Visibilidad de Planta', NULL);
INSERT INTO "DMES"."SC_MODULE_PERMISSION" ("ID_MODULE_PERMISSION", "NAME", "DESCRIPTION") 
	VALUES (2, 'Programación de Orden de Fabricación', NULL);
INSERT INTO "DMES"."SC_MODULE_PERMISSION" ("ID_MODULE_PERMISSION", "NAME", "DESCRIPTION") 
	VALUES (3, 'Gestión de la Calidad y la Trazabilidad', NULL);
INSERT INTO "DMES"."SC_MODULE_PERMISSION" ("ID_MODULE_PERMISSION", "NAME", "DESCRIPTION") 
	VALUES (4, 'Gestión del Mantenimiento', NULL);
INSERT INTO "DMES"."SC_MODULE_PERMISSION" ("ID_MODULE_PERMISSION", "NAME", "DESCRIPTION") 
	VALUES (5, 'Gestión de los Recursos', NULL);
INSERT INTO "DMES"."SC_MODULE_PERMISSION" ("ID_MODULE_PERMISSION", "NAME", "DESCRIPTION") 
	VALUES (6, 'Configuraciones', NULL);
INSERT INTO "DMES"."SC_MODULE_PERMISSION" ("ID_MODULE_PERMISSION", "NAME", "DESCRIPTION") 
	VALUES (7, 'Salir', NULL);

